stages:
- name: Codeception test
  steps:
  - runScriptConfig:
      image: loongson.harbor.cn/loongnix/php:7.3
      shellScript: |-
        apt-get update
        apt-get install -y --no-install-recommends git zip libsqlite3-dev zlib1g-dev libzip-dev
        docker-php-ext-install zip
        curl --silent --show-error https://getcomposer.org/installer | php
        ./composer.phar install -n --prefer-dist
        touch storage/testing.sqlite storage/database.sqlite
        cp .env.testing .env
        php artisan migrate
        php artisan migrate --env=testing --database=sqlite_testing --force
        ./vendor/bin/codecept build
        ./vendor/bin/codecept run
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: loongnix/php-example:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: loongson.harbor.cn
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_PASSWORD: admin
      PLUGIN_REGISTRY: loongson.harbor.cn
      PLUGIN_USERNAME: admin

- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
